### ISSUE TITLE
custom sidebar broken

### ISSUE THREAD

**Issue by KnutAtteslander** [ryan-roemer/sphinx-bootstrap-theme#177]
changes in
html_sidebars = {
    'sidebar': [
        'localtoc.html', 
        'sourcelink.html',
    ]
}
have no effect on sidebar

**Comment by KnutAtteslander** [comment]
Solution:
html_sidebars = {'**': ['localtoc.html']}

**Comment by svenevs** [comment]
Glad you found it, I'm including this in case other people hit the same thing (I remember hitting the same problem):

1. `html_sidebars` comes from Sphinx itself, the [documentation is here](http://www.sphinx-doc.org/en/stable/config.html#confval-html_sidebars).  As shown above, if you want it on every page, the key `**` is a glob that says "all".
2. In the `sphinx-bootstrap-theme` where the key [`"sidebar"`](https://github.com/ryan-roemer/sphinx-bootstrap-theme/blob/4722786a306842b0eaef4ab950732c7021860520/demo/source/conf.py#L193) hails from is because the sidebar is getting added specifically to the page named [`sidebar.rst`](https://github.com/ryan-roemer/sphinx-bootstrap-theme/blob/master/demo/source/sidebar.rst), which is generated into [`sidebar.html`](https://ryan-roemer.github.io/sphinx-bootstrap-theme/sidebar.html)
