### ISSUE TITLE
BUG: Selected col-md-width varies depending on Sphinx version

### ISSUE THREAD

**Issue by larsoner** [ryan-roemer/sphinx-bootstrap-theme#180]
With sphinx ~~1.5 (or maybe~~ <= 1.6 we got `col-md-12` for the main part of our pages:

http://mne-tools.github.io/stable/python_reference.html

Now with 1.7 / 1.8-dev we get col-md-9:

https://mne-tools.github.io/dev/python_reference.html

Anybody know why this would have changed / how to fix it?

**Comment by larsoner** [comment]
In the 1.7 release notes:

http://www.sphinx-doc.org/en/master/changes.html#id13

And

https://github.com/timhoffm/sphinx/commit/5def973298bcbda2a8d92847f4c0e820c95c610c

It seems like setting `body_max_width = body_min_width = '100%'` in `html_theme_options` of `conf.py` should revert this behavior, but it doesn't. I'll keep looking.

Although this change in default does suggest that the width should be skinnier, and thus the sidebar should be adjusted to be larger rather than forcing the body to be larger again.

**Comment by larsoner** [comment]
It looks like adding `nosidebar=True` to the `html_theme_options` dict has fixed it for us. Not sure where or why this happened due to Sphinx version, but I'll close since this workaround is good enough for our use case.

**Comment by svenevs** [comment]
Hi @larsoner thanks for the report.  I can't say for sure, but I think that the proposed fix in #181 should actually solve this.  Currently sidebars are getting added when they shouldn't be, and I think that's where `col-md-9` is coming from (the remaining space reserved for the sidebar).

If you comment out `nosidebar=True` and set `html_sidebars = {"**": []}` in your `conf.py`, does that get you the desired `col-md-12` again?  The linked PR will make it so that you do **not** have to explicitly set that, but I venture to say this is why `nosidebar=True` fixed the problem.

**Comment by svenevs** [comment]
Update: new version `0.6.5` should hopefully fix this without you needing `nosidebar=True` or setting `html_sidebars` in `conf.py`.  If you `pip3 install -U sphinx-bootstrap-theme` to get v0.6.5 (just released), does this issue remain or is it fixed?

**Comment by larsoner** [comment]
[Yes indeed](https://7721-1301584-gh.circle-artifacts.com/0/html/python_reference.html), thanks @svenevs !

**Comment by svenevs** [comment]
Woot! Thanks for confirming!
