### ISSUE TITLE
Font of lists looks too big

### ISSUE THREAD

**Issue by datapythonista** [ryan-roemer/sphinx-bootstrap-theme#184]
I'd say that some style is missing, that makes the font in the lists be larger than the one in the paragraphs, which causes a weird effect (IMHO).

This is how it looks in my case:

![pandas_doc](https://user-images.githubusercontent.com/10058240/41320132-6d1b1078-6e96-11e8-9b7b-a6617bdcdd16.png)

Same page as in #183, in case you want to check the html or the `conf.py`.

Thanks!

**Comment by ryan-roemer** [comment]
@datapythonista -- Can you check out this recently submitted PR and see if it solves the problem of this or your other issue? https://github.com/ryan-roemer/sphinx-bootstrap-theme/pull/182


thanks!

**Comment by datapythonista** [comment]
Hi @ryan-roemer, thanks for the very fast answer.

With the new PR, the sidebar is not rendered (without changing any setting I'd say), and the font size of the body is still larger.

![pandas_doc2](https://user-images.githubusercontent.com/10058240/41322392-a3384928-6ea0-11e8-8506-efa6de969ab0.png)

**Comment by ryan-roemer** [comment]
@datapythonista -- I would ❤️ to have `pandas` on this theme. But I'm slammed right now and going on vacation in a few days, so it's likely going to be figuring things out over a course of weeks.

I'll try and dig in when I get a moment, and just keep filing issues for anything else you find along the way!

**Comment by datapythonista** [comment]
Sure, don't worry. I'll be working on the doc changes in pandas, as there is much more than the theme. If you don't have time, I'll take a look myself at the theme code and send you PRs.

It already looks really great, without any changes. I don't think there will be much more than those two minor issues.

**Comment by ashafer01** [comment]
So the list font size issue is actually because you have a list within a blockquote. If you remove the leading space(s) from the list elements in your rst source it should normalize.

**Comment by svenevs** [comment]
Specifically, what @ashafer01 is saying is the larger font size is from bootstrap, via `blockquote`:

![blockquote](https://user-images.githubusercontent.com/5871461/41324120-a44619b4-6e67-11e8-98e1-d0b9756f4992.jpeg)

You've been trapped by one of the more subtle reStructureText whitespace rules.  [Block quotes are just indented space](http://docutils.sourceforge.net/docs/user/rst/quickref.html#block-quotes).  As stated above, remove the leading space

```rst
v
 * A set of labeled array data structures, the primary of which are...
* A set of labeled array data structures, the primary of which are...
```

FWIW, because this rule really bothers me, what the linked docutils blockquote docs state but do not show is how you can make a blockquote _explicit_ using an "empty comment".  Comments in RST are `..`, so you can do

```rst
..
    * A set of labeled array data structures, the primary of which are...
```

If you want it to be a little more "obvious" (a relative term here for sure), being indented by four spaces underneat that `..` "makes it a blockquote too".

If you want it to remain in a blockquote, but not have larger font, you'll need to add some CSS to your project, possibly just overriding `blockquote` altogether

```css
/* override bootstrap making <blockquote> text larger */
.blockquote { font-size: 14px ! important; }
```

Let us know if you need help coordinating extra CSS with Sphinx :)

I'm going to close this, if you need further help please re-open (I'm with ryan, having `pandas` using this theme would be super cool)!

**Comment by datapythonista** [comment]
Thank you everybody for helping with this. I created a PR for pandas, to fix all the lists indentation.

https://github.com/pandas-dev/pandas/issues/21518
